---
elasticsearch:
    hosts:
      el-instance:
        ansible_host: 172.29.251.69
kibana:
    hosts:
      k-instance:
        ansible_host: 172.29.249.243
filebeat:
    hosts:
      f-instance:
        ansible_host: 172.29.243.248