---
all:
  hosts:
    all:
    el-instance:
      hosts:
        ansible_host: 172.29.251.69
    k-instance:
      hosts:
        ansible_host: 172.29.249.243
    f-instance:
      hosts:
        ansible_host: 172.29.243.248