---
all:
 hosts:
elasticsearch:
 hosts:
  el-instance:
   ansible_host: 172.29.251.69
vars:
    ansible_connection: ssh
    ansible_user: root
kibana:
 hosts:
  k-instance:
   ansible_host: 172.29.249.243
vars:
    ansible_connection: ssh
    ansible_user: root
app:
 hosts:
  application-instance:
   ansible_host: 172.29.243.48
vars:
    ansible_connection: ssh
    ansible_user: root