---
all:
 hosts:
 vars:
    ansible_connection: ssh
    ansible_user: root
elasticsearch:
 hosts:
  el-instance:
   ansible_host: 192.168.1.6
kibana:
 hosts:
  k-instance:
   ansible_host: 192.168.1.5
app:
 hosts:
  application-instance:
   ansible_host: 192.168.1.4