---
  - src: git@github.com:avo1yanskiy/kibana-role.git
    scm: git
    version: 2.0.0
    name: kibana_role

  - src: https://github.com/netology-code/mnt-homeworks-ansible.git
    scm: git
    version: 2.0.0
    name: elasticsearch_role


