---
- name: Firewall
  hosts: all
  tasks:
   - name: Disabled Firewall
     become: true
     service:
      name: firewalld
      state: stopped
      enabled: False
      tags: firewall
- name: Install MC
  hosts: all
  tasks:
   - name: MC
     become: true
     yum:
      name: mc
      state: present
      tags: mc
- name: Install Elasticsearch
  hosts: elasticsearch
  handlers:
    - name: restart Elasticsearch
      become: true
      service:
        name: elasticsearch
        state: restarted
        enabled: true
  tasks:
    - name: "Download Elasticsearch's rpm"
      get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
        dest: "/tmp/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
      register: download_elastic
      until: download_elastic is succeeded
    - name: Install Elasticsearch
      become: true
      yum:
        name: "/tmp/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
        state: present
        tags: 
          - elasticsearch
    - name: Configure Elasticsearch
      become: true
      template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
      notify: restart Elasticsearch
- name: Install Kibana
  hosts: kibana
  handlers:
    - name: restart kibana
      become: true
      service:
        name: kibana
        state: restarted
        tags: 
          - kibana
  tasks:
    - name: Download Kibana rpm
      get_url:
        url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm"
        dest: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
      register: download_kibana
      until: download_kibana is succeeded
    - name: Install Kibana
      become: true
      yum:
        name: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
        state: present
        tags: 
          - kibana
    - name: Start Kibana
      ansible.builtin.service:
        name: kibana
        state: started
    - name: Configure Kibana
      become: true
      template:
        src: kibana.yml.j2
        dest: /etc/kibana/kibana.yml
      notify: restart kibana
      tags: 
          - kibana
- name: Install filebeat
  hosts: application-instance
  handlers:
    - name: restart filebeat
      become: true
      service:
        name: filebeat
        state: restarted
  tasks:
    - name: "Download filebeat rpm"
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{filebeat_version}}-x86_64.rpm"
        dest: "/tmp/filebeat-{{filebeat_version}}-x86_64.rpm"
      register: filebeat
      until: filebeat is succeeded
    - name: Install filebeat
      become: true
      yum:
        name: "/tmp/filebeat-{{filebeat_version}}-x86_64.rpm"
        state: present
      notify: restart filebeat
    - name: Start filebeat
      ansible.builtin.service:
        name: filebeat
        state: started
    - name: Configure filebeat
      become: true
      template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
      notify: restart filebeat
    - name: Set filebeat systemwork
      become: true
      command:
        cmd: filebeat modules enable system
        chdir: /usr/share/filebeat/bin
    - name: zagruzka Kibana dashboard
      become: true
      command:
        cmd: filebeat setup
        chdir: /usr/share/filebeat/bin
      register: filebeat_setup
      until: filebeat_setup is succeeded
      notify: restart filebeat
